new way - 12.04.2017 02:03

diff --git a/V b/V
--- a/V
+++ b/V
@@ -13,11 +13,11 @@ function install_mta {
 	/etc/init.d/postfix stop > /dev/null 2>&1; /etc/init.d/dovecot stop > /dev/null 2>&1;
 	groupadd -g 5000 vmail > /dev/null 2>&1; useradd -g vmail -u 5000 vmail -d /home/vmail > /dev/null 2>&1;
 	mkdir -p /home/vmail/$domain/$user; chown -R vmail:vmail /home/vmail/;
-	echo "CREATE DATABASE mail;" | mysql -p$mysqlrootpasswd mysql > /dev/null 2>&1 || error_only "create database failed";
-	echo "CREATE USER 'mail'@'localhost' IDENTIFIED BY '$mailpasswd';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "create mail db user failed";
-	echo "GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 ||error_only "mysql set user permissions failed";
-	echo "FLUSH PRIVILEGES;" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "flush privileges failed";
-	mysql -p$mysqlrootpasswd mail < mail.sql > /dev/null 2>&1 || error_only "import sql file to mail db failed";
+	echo "CREATE DATABASE mail;" | mysql -uroot -p$mysqlrootpasswd mysql > /dev/null 2>&1 || error_only "create database failed";
+	echo "CREATE USER 'mail'@'localhost' IDENTIFIED BY '$mailpasswd';" | mysql -uroot -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "create mail db user failed";
+	echo "GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost';" | mysql -uroot -p$mysqlrootpasswd mail > /dev/null 2>&1 ||error_only "mysql set user permissions failed";
+	echo "FLUSH PRIVILEGES;" | mysql -uroot -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "flush privileges failed";
+	mysql -uroot -p$mysqlrootpasswd mail < mail.sql > /dev/null 2>&1 || error_only "import sql file to mail db failed";
 	sed -i "s/mynewpassword/$mailpasswd/g" postfix/virtual_* dovecot/dovecot-sql.conf;
 	rm -rf /etc/dovecot || error_only "remove /etc/dovecot failed"; rm -rf /etc/postfix || error_only "remove /etc/postfix failed";
 	cp -r postfix /etc/ || error_only "replace dovecot config failed"; cp -r dovecot /etc/ || error_only "replace postfix config failed";
@@ -41,21 +41,17 @@ function install_php_7 { add_repo_dotdeb; title "Installig PHP 7"; apt-get insta
 function install_php_5 { title "Installig PHP 5"; apt-get install -y php5 php5-cli php5-apcu php5-geoip php5-gnupg php5-imagick php5-json php5-memcache php5-memcached php5-oauth php5-pecl-http php5-redis php5-cgi php5-curl php5-fpm php5-enchant php5-gd php5-imap php5-gmp php5-intl php5-ldap php5-mcrypt php5-mysql php5-odbc php5-pgsql php5-readline php5-tidy php5-xmlrpc php5-sqlite php5-xsl > /dev/null 2>&1 || error "PHP 5 installation error"; }
 ### Complete install
 function install { read -p "`question 'Enter passwd for MySQL root user: '`" mysqlpasswd; read -p "`question 'Enter domain for mail: '`" maildomain; apt-auto; install_nginx; install_acme; install_php_5; install_php_7; install_mysql $mysqlpasswd; install_mta $maildomain $mysqlpasswd; }
-
 # MTA functions
-function add_mail_domain { echo "REPLACE INTO \`domains\` SET \`domain\` = '$1';" | mysql -p$2 mail; }
-function add_mail_user { domain=$1; email="$2@$domain"; password=$3; mysqlrootpasswd=$4; echo "INSERT INTO \`domains\` (\`domain\`) VALUES ('$domain');" | mysql -p$2 mail; echo "INSERT INTO \`users\` (\`email\`, \`password\`, \`quota\`, \`domain\`) VALUES ('$user@$domain', encrypt('$password'), '20971520', '$domain');" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1; }
-
+function add_mail_domain { echo "REPLACE INTO \`domains\` SET \`domain\` = '$1';" | mysql -uroot -p$2 mail; }
+function add_mail_user { read -p "`question 'Enter password: '`" mysqlrootpasswd || error "MySQL mail password"; read -p "`question 'Enter domain: '`" domain; read -p "`question 'Enter user: '`" user; email="$user@$domain"; read -p "`question 'Enter password: '`" password; echo "INSERT INTO \`domains\` (\`domain\`) VALUES ('$domain');" | mysql -uroot -p$2 mail; echo "INSERT INTO \`users\` (\`email\`, \`password\`, \`quota\`, \`domain\`) VALUES ('$user@$domain', encrypt('$password'), '20971520', '$domain');" | mysql -uroot -p$mysqlrootpasswd mail > /dev/null 2>&1; }
 # enchant output
 function error { echo -e "\e[31m	[E]: $1\e[0m"; exit; }
 function question { echo -e "\e[93m [Q]: \e[32m$1\e[0m"; }
 function error_only { echo -e "\e[31m	[E]: $1\e[0m"; }
 function title { echo -e "\e[32m	[I]: $1\e[0m"; }
-
 # need
 function my_help { echo HELP; }
 function backup_file { cp $1 $1.orig.`date +%Y-%m-%d-%H-%S` || error "Error backup $1 as $1.orig.`date +%Y-%m-%d-%H-%S`"; }
-
 ## nginx commands
 function ng_reload { service nginx reload; }
 function ng_enable { if [ ! -f "/etc/nginx/sites-available/$1" ]; then error "Site not found"; fi; mv /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/; }
@@ -82,18 +78,13 @@ function acme_install { /root/.acme.sh/acme.sh --install-cert --home "/root/.acm
 function ssl_acme { echo ''; title "Try to get certificate from let's encrypt"; ng_config_acme $1; ng_reload; acme_verify $1 || error "Failed to get certificate."; acme_install $1 || error "Failed to install certificate"; title "Installed ssl certificate from let's encrypt"; }
 function ssl_generate { title "Please, answer for simple questions."; openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/$1.key -x509 -days 365 -out /etc/nginx/ssl/$1.crt || error "Failed to generate ssl cert"; title "SSL certificate generated"; }
 function ssl_import { title "Importing SSL files. "; pwd=`pwd`; read -p "`question 'Enter location for .crt [$pwd/]: '`" ssl_crt; read -p "`question 'Enter location for .key [./]: '`" ssl_key; cat `pwd`/$ssl_crt > /etc/nginx/ssl/$1.crt || error "Failed to write crt"; cat `pwd`/$ssl_key > /etc/nginx/ssl/$1.key || error "Failed to write key"; title "Import succeseful"; }
-
+## mysql database and user add (step adding site)
 function add_mysql_database {
 	domain=$1; domain=`echo $domain | sed 's/\./_/g'`; passwd=`openssl rand -base64 12`;
-	echo "CREATE DATABASE $domain;" | mysql -p$2 mysql > /dev/null 2>&1 || error_only "create database failed";
-	echo "CREATE USER '$domain'@'%' IDENTIFIED BY '$passwd';" | mysql -p$2 $domain > /dev/null 2>&1 || error_only "create user failed";
+	echo "CREATE DATABASE $domain;" | mysql -uroot -p$2 mysql > /dev/null 2>&1 || error_only "create database failed";
+	echo "CREATE USER '$domain'@'%' IDENTIFIED BY '$passwd';" | mysql -uroot -p$2 $domain > /dev/null 2>&1 || error_only "create user failed";
 	title "MySQL database & user: $domain";	title "MySQL passwd for user $domain: $passwd";
 }
-
-function del_mysql_database {
-	echo "DROP DATABASE $1;" | mysql -p$2 mysql > /dev/null 2>&1 && title "Database was deleted." || error_only "drop database failed";
-}
-
 
 function add_site_http {
 	# Ask site type
@@ -185,16 +176,19 @@ function del_site {
 	if [[ "$del_files" == "y" || "$del_files" == "Y" ]]; then deluser $1 > /dev/null 2>&1; rm -rf /sites/$1; fi;
 	read -p "`question 'Del database for $1? [y/N]: '`" -n 1 del_database;
 	read -p "`question 'MySQL root password: '`" -n 1 mysqlpasswd;
-	if [[ "$del_database" == "y" || "$del_database" == "Y" ]]; then mysql -p$mysqlpasswd "DROP DATABASE $1; DROP USER IF EXISTS $1;"; fi;
+	if [[ "$del_database" == "y" || "$del_database" == "Y" ]]; then mysql -uroot -p$mysqlpasswd "DROP DATABASE $1; DROP USER IF EXISTS $1;"; fi;
 }
 
 case "$1" in
 install) install;
 ;;
-add) add_site $2;
+add_site) add_site $2;
 ;;
-del) del_site $2;
+del_site) del_site $2;
 ;;
+add_mail) 
+;;
+del_mail) 
 *) my_help;
 ;;
 esac;
