new way

diff --git a/V b/V
--- a/V
+++ b/V
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# enchant output
+function error { echo -e "\e[31m	[E]: $1\e[0m"; exit; }
+function question { echo -e "\e[93m [Q]: \e[32m$1\e[0m"; }
+function error_only { echo -e "\e[31m	[E]: $1\e[0m"; }
+function title { echo -e "\e[32m	[I]: $1\e[0m"; }
+function my_help { echo HELP; }
+
 # nginx config
 ## http config
 function ng_http_html { mkdir -p /sites/$1/public; cat <<< " server { listen 80; root /sites/$1/public; index index.php index.html index.htm; server_name $1;} " > /etc/nginx/sites-enabled/$1;}
@@ -14,12 +21,13 @@ function ng_https_proxy { mkdir -p /sites/$1/public; cat <<< " server { listen 4
 ## rewrite
 function ng_rewrite_www { cat <<< " server { server_name www.$1; listen 80; return 301 http://$1\$request_uri; } " >> /etc/nginx/sites-enabled/$1; }
 function ng_rewrite_https { cat <<< " server { server_name $1; listen 80; return 301 https://$1\$request_uri? permanent; } " >> /etc/nginx/sites-enabled/$1; }
-
-
+## acme - let`s encrypt cert`s
+function acme_verify { echo ''; mkdir -p /sites/$1/public/.well-known/acme-challenge/; ng_config_acme $1; ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1; service nginx restart > /dev/null 2>&1; /root/.acme.sh/acme.sh --issue -d $1 -d www.$1 -w /sites/$1/public --home "/root/.acme.sh" > /dev/null 2>&1 || error "Failed to get cert"; rm /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1; }
+function acme_install { /root/.acme.sh/acme.sh --install-cert --home "/root/.acme.sh" -d $1 --cert-file /etc/nginx/ssl/$1.crt --key-file /etc/nginx/ssl/$1.key --fullchain-file /etc/nginx/ssl/$1.ca --reloadcmd "service nginx reload" > /dev/null 2>&1 || error "Failed to install cert" ; }
 
 function add_site {
 	if [ -z "$1" ]; then error "Specify domain name."; fi;
-	read -p "`question 'Add site $1?: '`" add_site;
-	
+	read -p "`question 'Add site $1? [y/N]: '`" -n 1 add_site;
+	if [[ "$add_site" != "y" || "$add_site" != "Y" ]]; then error "Aborted"; fi;
 }
 
