new way - 12.04.2017 02:03

diff --git a/V b/V
--- a/V
+++ b/V
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+. ./VE_install
+
 # enchant output
 function error { echo -e "\e[31m	[E]: $1\e[0m"; exit; }
 function question { echo -e "\e[93m [Q]: \e[32m$1\e[0m"; }
@@ -30,8 +32,8 @@ function ng_rewrite_https { cat <<< " server { server_name $1; listen 80; return
 function acme_verify { echo ''; mkdir -p /sites/$1/public/.well-known/acme-challenge/; ng_config_acme $1; ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-available/$1; service nginx restart > /dev/null 2>&1; /root/.acme.sh/acme.sh --issue -d $1 -d www.$1 -w /sites/$1/public --home "/root/.acme.sh" > /dev/null 2>&1 || error "Failed to get cert"; rm /etc/nginx/sites-available/$1; }
 function acme_install { /root/.acme.sh/acme.sh --install-cert --home "/root/.acme.sh" -d $1 --cert-file /etc/nginx/ssl/$1.crt --key-file /etc/nginx/ssl/$1.key --fullchain-file /etc/nginx/ssl/$1.ca --reloadcmd "service nginx reload" > /dev/null 2>&1 || error "Failed to install cert" ; }
 function ssl_acme { title "Try to get certificate from let's encrypt"; ng_config_acme $1; ng_reload; acme_verify $1 || error "Failed to get certificate."; acme_install $1 || error "Failed to install certificate"; title "Installed ssl certificate from let's encrypt"; }
-function ssl_generate { title "Please, answer for simple questions."; openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/$1.key -x509 -days 365 -out /etc/nginx/ssl/$1.crt || error "Failed to generate ssl cert"; }
-function ssl_import { title "Importing SSL files. "; pwd=`pwd`; read -p "`question 'Enter location for .crt [$pwd/]: '`" ssl_crt; read -p "`question 'Enter location for .key [./]: '`" ssl_key; cat `pwd`/$ssl_crt > /etc/nginx/ssl/$1.crt || error "Failed to write crt"; cat `pwd`/$ssl_key > /etc/nginx/ssl/$1.key || error "Failed to write key"; title "Import succeseful": }
+function ssl_generate { title "Please, answer for simple questions."; openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/$1.key -x509 -days 365 -out /etc/nginx/ssl/$1.crt || error "Failed to generate ssl cert"; title "SSL certificate generated"; }
+function ssl_import { title "Importing SSL files. "; pwd=`pwd`; read -p "`question 'Enter location for .crt [$pwd/]: '`" ssl_crt; read -p "`question 'Enter location for .key [./]: '`" ssl_key; cat `pwd`/$ssl_crt > /etc/nginx/ssl/$1.crt || error "Failed to write crt"; cat `pwd`/$ssl_key > /etc/nginx/ssl/$1.key || error "Failed to write key"; title "Import succeseful"; }
 
 function add_site_http {
 	echo -e "\t1. [HTML]\n\t2. PHP 5\n\t3. PHP 7\n\t4. Proxy";
@@ -47,7 +49,7 @@ function add_site_http {
 	;;
 	*) ng_http_html $1; ng_enable $1; ng_reload; error_only "Wrong number."; title "Site $1 was created as html site.";
 	;;
-	esac
+	esac;
 }
 
 function add_site_https {
@@ -60,9 +62,9 @@ function add_site_https {
 	;;
 	3) ssl_import $1;
 	;;
-	*) 
+	*) rm -rf /sites/$1; deluser $1 > /dev/null 2>&1; error "Must have action number for ssl adding";
 	;;
-
+	esac
 	echo -e "\n\t1. [HTML]\n\t2. PHP 5\n\t3. PHP 7\n\t4. Proxy";
 	read -p "`question 'Site type for $1? '`" -n 1 site_type;
 	case "$site_type" in
@@ -77,6 +79,7 @@ function add_site_https {
 	*) ng_https_html $1; ng_enable $1; ng_reload; error_only "Wrong number."; title "Site $1 was created as html site.";
 	;;
 	esac
+	title "Nginx config ready and applied";
 }
 
 function add_site {
@@ -100,6 +103,8 @@ function add_site {
 	;;
 	*) add_site_http $1;
 	;;
+	esac;
+	title "Nginx config ready and applied";
 }
 
 function del_site {
@@ -113,3 +118,25 @@ function del_site {
 	if [[ "$del_database" == "y" || "$del_database" == "Y" ]]; then mysql -p$mysqlpasswd "DROP DATABASE $1; DROP USER IF EXISTS $1;"; fi;
 
 }
+
+case "$1" in
+install) install;
+;;
+add) add_site $2;
+;;
+del) del_site $2;
+;;
+*) my_help;
+;;
+esac;
+
+
+
+
+
+
+
+
+
+
+
