new way - 12.04.2017 02:03

diff --git a/V b/V
--- a/V
+++ b/V
@@ -57,9 +57,10 @@ function ssl_generate { title "Please, answer for simple questions."; openssl re
 function ssl_import { title "Importing SSL files. "; pwd=`pwd`; read -p "`question 'Enter location for .crt [$pwd/]: '`" ssl_crt; read -p "`question 'Enter location for .key [./]: '`" ssl_key; cat `pwd`/$ssl_crt > /etc/nginx/ssl/$1.crt || error "Failed to write crt"; cat `pwd`/$ssl_key > /etc/nginx/ssl/$1.key || error "Failed to write key"; title "Import succeseful"; }
 
 function add_mysql_database {
-	domain=$1; mysqlrootpasswd=$2;
+	domain=$1; mysqlrootpasswd=$2; passwd=`openssl rand -base64 10`;
 	echo "CREATE DATABASE '$domain';" | mysql -p$mysqlrootpasswd mysql > /dev/null 2>&1 || errot_only "create database failed";
-	echo "CREATE USER '$domain'@'localhost' IDENTIFIED BY '$password';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "create user failed";
+	echo "CREATE USER '$domain'@'%' IDENTIFIED BY '$password';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "create user failed";
+	title "MySQL passwd for user $domain: $password";
 }
 
 function add_site_http {
