new way - 12.04.2017 02:03

diff --git a/V b/V
--- a/V
+++ b/V
@@ -11,10 +11,10 @@ function my_help { echo HELP; }
 
 ## nginx commands
 function ng_reload { service nginx reload; }
-function ng_enable { if [ ! -f "/etc/nginx/sites-available/$1" ]; then error "Site not found"; fi; mv /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1; }
+function ng_enable { if [ ! -f "/etc/nginx/sites-enabled/$1" ]; then error "Site not found"; fi; mv //etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1; }
 function ng_disable { if [ ! -f "/etc/nginx/sites-enabled/$1" ]; then error "Site not found"; fi; mv /etc/nginx/sites-enabled/$1 /etc/nginx/sites-available/$1; }
 function ng_ls_enabled { ls /etc/nginx/sites-enabled/$1; }
-function ng_ls_disabled { ls /etc/nginx/sites-available/$1; }
+function ng_ls_disabled { ls /etc/nginx/sites-enabled/$1; }
 ## http config
 function ng_http_html { cat <<< " server { listen 80; root /sites/$1/public; index index.php index.html index.htm; server_name $1;} " > /etc/nginx/sites-available/$1;}
 function ng_http_php_5 { cat <<< " server { listen 80; root /sites/$1/public; index index.php index.html index.htm; server_name $1; client_max_body_size 100m; location / { index  index.php index.html; rewrite  ^(.*)\$ /index.php?\$args last; } location ~ \.php\$ { try_files \$uri = 404; fastcgi_pass unix:/var/run/php5-fpm.sock; fastcgi_index index.php; fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name; include fastcgi_params; } } " > /etc/nginx/sites-available/$1; }
@@ -29,10 +29,10 @@ function ng_https_proxy { cat <<< " server { listen 443 ssl; ssl_certificate /et
 function ng_rewrite_www { cat <<< " server { server_name www.$1; listen 80; return 301 http://$1\$request_uri; } " >> /etc/nginx/sites-available/$1; }
 function ng_rewrite_https { cat <<< " server { server_name $1; listen 80; return 301 https://$1\$request_uri? permanent; } " >> /etc/nginx/sites-available/$1; }
 ## acme - let`s encrypt cert`s
-function ng_config_acme { cat <<< " server {listen 80; root /sites/$1/public; index index.html; server_name $1 www.$1; location /.well-known/acme-challenge {allow all;autoindex on;} } " > /etc/nginx/sites-enabled/$1; } 
-function acme_verify { echo ''; mkdir -p /sites/$1/public/.well-known/acme-challenge/; ng_config_acme $1; service nginx restart > /dev/null 2>&1; /root/.acme.sh/acme.sh --force --issue -d $1 -d www.$1 -w /sites/$1/public --home "/root/.acme.sh" > /dev/null 2>&1 || error "Failed to get cert"; rm /etc/nginx/sites-available/$1; }
+function ng_config_acme { cat <<< " server {listen 80; root /sites/$1/public; index index.html; server_name $1 www.$1; location /.well-known/acme-challenge {allow all;autoindex on;} } " > /etc/nginx/sites-available/$1; ng_enable $1; } 
+function acme_verify { echo ''; mkdir -p /sites/$1/public/.well-known/acme-challenge/; ng_config_acme $1; service nginx restart > /dev/null 2>&1; /root/.acme.sh/acme.sh --force --issue -d $1 -d www.$1 -w /sites/$1/public --home "/root/.acme.sh" > /dev/null 2>&1 || error "Failed to get cert"; rm /etc/nginx/sites-enabled/$1; }
 function acme_install { /root/.acme.sh/acme.sh --install-cert --home "/root/.acme.sh" -d $1 --cert-file /etc/nginx/ssl/$1.crt --key-file /etc/nginx/ssl/$1.key --fullchain-file /etc/nginx/ssl/$1.ca --reloadcmd "service nginx reload" > /dev/null 2>&1 || error "Failed to install cert" ; }
-function ssl_acme { title "Try to get certificate from let's encrypt"; ng_config_acme $1; ng_reload; acme_verify $1 || error "Failed to get certificate."; acme_install $1 || error "Failed to install certificate"; title "Installed ssl certificate from let's encrypt"; }
+function ssl_acme { echo ''; title "Try to get certificate from let's encrypt"; ng_config_acme $1; ng_reload; acme_verify $1 || error "Failed to get certificate."; acme_install $1 || error "Failed to install certificate"; title "Installed ssl certificate from let's encrypt"; }
 function ssl_generate { title "Please, answer for simple questions."; openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/$1.key -x509 -days 365 -out /etc/nginx/ssl/$1.crt || error "Failed to generate ssl cert"; title "SSL certificate generated"; }
 function ssl_import { title "Importing SSL files. "; pwd=`pwd`; read -p "`question 'Enter location for .crt [$pwd/]: '`" ssl_crt; read -p "`question 'Enter location for .key [./]: '`" ssl_key; cat `pwd`/$ssl_crt > /etc/nginx/ssl/$1.crt || error "Failed to write crt"; cat `pwd`/$ssl_key > /etc/nginx/ssl/$1.key || error "Failed to write key"; title "Import succeseful"; }
 
@@ -87,7 +87,7 @@ function add_site {
 	if [ -z "$1" ]; then error "Specify domain name."; fi;
 	read -p "`question 'Add site? [y/N]: '`" -n 1 add_site;
 	if [[ "$add_site" == "n" || "$add_site" == "N" || "$add_site" == "" ]]; then error "Aborted"; fi;
-	rm /etc/nginx/sites-enabled/$1 /etc/nginx/sites-available/$1 > /dev/null 2>&1;
+	rm /etc/nginx/sites-enabled/$1 /etc/nginx/sites-enabled/$1 > /dev/null 2>&1;
 	echo -e "\n\n\n\n\n\n" | adduser --quiet --disabled-password --shell /bin/bash --home /sites/$1 --ingroup www-data $1 --force-badname > /dev/null 2>&1;
 	echo '';
 	read -p "`question 'Password : '`" passwd;
